
version: '3.7'
services:
  forkscan:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'
      - FLASK_DEBUG=1
    command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
