version: '3.7'
services:
  forkscan:
    image: mk0x/docker-fork-scan
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
